# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kontrola_arduino_test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 801, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Kontrola_diod_check = QtWidgets.QCheckBox(self.frame)
        self.Kontrola_diod_check.setGeometry(QtCore.QRect(10, 10, 121, 23))
        self.Kontrola_diod_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Kontrola_diod_check.setAutoFillBackground(False)
        self.Kontrola_diod_check.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Kontrola_diod_check.setChecked(False)
        self.Kontrola_diod_check.setObjectName("Kontrola_diod_check")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 40, 111, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Button_OFF_Dioda3 = QtWidgets.QRadioButton(self.frame_2)
        self.Button_OFF_Dioda3.setGeometry(QtCore.QRect(10, 90, 112, 23))
        self.Button_OFF_Dioda3.setChecked(False)
        self.Button_OFF_Dioda3.setObjectName("Button_OFF_Dioda3")
        self.Button_ON_Dioda3 = QtWidgets.QRadioButton(self.frame_2)
        self.Button_ON_Dioda3.setGeometry(QtCore.QRect(10, 60, 112, 23))
        self.Button_ON_Dioda3.setObjectName("Button_ON_Dioda3")
        self.Label_Dioda3 = QtWidgets.QLabel(self.frame_2)
        self.Label_Dioda3.setGeometry(QtCore.QRect(20, 10, 67, 31))
        self.Label_Dioda3.setObjectName("Label_Dioda3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(160, 40, 111, 131))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Button_OFF_Dioda3_2 = QtWidgets.QRadioButton(self.frame_3)
        self.Button_OFF_Dioda3_2.setGeometry(QtCore.QRect(10, 90, 112, 23))
        self.Button_OFF_Dioda3_2.setChecked(False)
        self.Button_OFF_Dioda3_2.setObjectName("Button_OFF_Dioda3_2")
        self.Button_ON_Dioda3_2 = QtWidgets.QRadioButton(self.frame_3)
        self.Button_ON_Dioda3_2.setGeometry(QtCore.QRect(10, 60, 112, 23))
        self.Button_ON_Dioda3_2.setObjectName("Button_ON_Dioda3_2")
        self.Label_Dioda3_2 = QtWidgets.QLabel(self.frame_3)
        self.Label_Dioda3_2.setGeometry(QtCore.QRect(10, 10, 67, 41))
        self.Label_Dioda3_2.setObjectName("Label_Dioda3_2")
        self.Label_Dioda3_3 = QtWidgets.QLabel(self.frame)
        self.Label_Dioda3_3.setGeometry(QtCore.QRect(300, 30, 67, 17))
        self.Label_Dioda3_3.setObjectName("Label_Dioda3_3")
        self.Label_Dioda3_4 = QtWidgets.QLabel(self.frame)
        self.Label_Dioda3_4.setGeometry(QtCore.QRect(430, 30, 67, 17))
        self.Label_Dioda3_4.setObjectName("Label_Dioda3_4")
        self.Button_ON_Dioda3_3 = QtWidgets.QRadioButton(self.frame)
        self.Button_ON_Dioda3_3.setGeometry(QtCore.QRect(310, 60, 112, 23))
        self.Button_ON_Dioda3_3.setObjectName("Button_ON_Dioda3_3")
        self.Button_ON_Dioda3_4 = QtWidgets.QRadioButton(self.frame)
        self.Button_ON_Dioda3_4.setGeometry(QtCore.QRect(430, 60, 112, 23))
        self.Button_ON_Dioda3_4.setObjectName("Button_ON_Dioda3_4")
        self.Button_OFF_Dioda3_3 = QtWidgets.QRadioButton(self.frame)
        self.Button_OFF_Dioda3_3.setGeometry(QtCore.QRect(310, 100, 112, 23))
        self.Button_OFF_Dioda3_3.setChecked(False)
        self.Button_OFF_Dioda3_3.setObjectName("Button_OFF_Dioda3_3")
        self.Button_OFF_Dioda3_4 = QtWidgets.QRadioButton(self.frame)
        self.Button_OFF_Dioda3_4.setGeometry(QtCore.QRect(430, 100, 112, 23))
        self.Button_OFF_Dioda3_4.setChecked(False)
        self.Button_OFF_Dioda3_4.setObjectName("Button_OFF_Dioda3_4")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(510, 30, 121, 121))
        self.widget.setObjectName("widget")
        self.Button_OFF_Dioda3_5 = QtWidgets.QRadioButton(self.widget)
        self.Button_OFF_Dioda3_5.setGeometry(QtCore.QRect(10, 80, 112, 23))
        self.Button_OFF_Dioda3_5.setChecked(False)
        self.Button_OFF_Dioda3_5.setObjectName("Button_OFF_Dioda3_5")
        self.Button_ON_Dioda3_5 = QtWidgets.QRadioButton(self.widget)
        self.Button_ON_Dioda3_5.setGeometry(QtCore.QRect(10, 40, 112, 23))
        self.Button_ON_Dioda3_5.setObjectName("Button_ON_Dioda3_5")
        self.Label_Dioda3_5 = QtWidgets.QLabel(self.widget)
        self.Label_Dioda3_5.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.Label_Dioda3_5.setObjectName("Label_Dioda3_5")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(120, 110, 121, 121))
        self.widget_2.setObjectName("widget_2")
        self.Button_OFF_Dioda3_6 = QtWidgets.QRadioButton(self.widget_2)
        self.Button_OFF_Dioda3_6.setGeometry(QtCore.QRect(10, 80, 112, 23))
        self.Button_OFF_Dioda3_6.setChecked(False)
        self.Button_OFF_Dioda3_6.setObjectName("Button_OFF_Dioda3_6")
        self.Button_ON_Dioda3_6 = QtWidgets.QRadioButton(self.widget_2)
        self.Button_ON_Dioda3_6.setGeometry(QtCore.QRect(10, 40, 112, 23))
        self.Button_ON_Dioda3_6.setObjectName("Button_ON_Dioda3_6")
        self.Label_Dioda3_6 = QtWidgets.QLabel(self.widget_2)
        self.Label_Dioda3_6.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.Label_Dioda3_6.setObjectName("Label_Dioda3_6")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setGeometry(QtCore.QRect(650, 30, 121, 121))
        self.widget_3.setObjectName("widget_3")
        self.Button_OFF_Dioda3_7 = QtWidgets.QRadioButton(self.widget_3)
        self.Button_OFF_Dioda3_7.setGeometry(QtCore.QRect(10, 80, 112, 23))
        self.Button_OFF_Dioda3_7.setChecked(False)
        self.Button_OFF_Dioda3_7.setObjectName("Button_OFF_Dioda3_7")
        self.Button_ON_Dioda3_7 = QtWidgets.QRadioButton(self.widget_3)
        self.Button_ON_Dioda3_7.setGeometry(QtCore.QRect(10, 40, 112, 23))
        self.Button_ON_Dioda3_7.setObjectName("Button_ON_Dioda3_7")
        self.Label_Dioda3_7 = QtWidgets.QLabel(self.widget_3)
        self.Label_Dioda3_7.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.Label_Dioda3_7.setObjectName("Label_Dioda3_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Kontrola_diod_check.setText(_translate("MainWindow", "Kontrola diod"))
        self.Button_OFF_Dioda3.setText(_translate("MainWindow", "OFF"))
        self.Button_ON_Dioda3.setText(_translate("MainWindow", "ON"))
        self.Label_Dioda3.setText(_translate("MainWindow", "Dioda 1\n"
" LABEL"))
        self.Button_OFF_Dioda3_2.setText(_translate("MainWindow", "OFF"))
        self.Button_ON_Dioda3_2.setText(_translate("MainWindow", "ON"))
        self.Label_Dioda3_2.setText(_translate("MainWindow", "Dioda 2\n"
" LABEL"))
        self.Label_Dioda3_3.setText(_translate("MainWindow", "Dioda 3"))
        self.Label_Dioda3_4.setText(_translate("MainWindow", "Dioda 4"))
        self.Button_ON_Dioda3_3.setText(_translate("MainWindow", "ON"))
        self.Button_ON_Dioda3_4.setText(_translate("MainWindow", "ON"))
        self.Button_OFF_Dioda3_3.setText(_translate("MainWindow", "OFF"))
        self.Button_OFF_Dioda3_4.setText(_translate("MainWindow", "OFF"))
        self.Button_OFF_Dioda3_5.setText(_translate("MainWindow", "OFF"))
        self.Button_ON_Dioda3_5.setText(_translate("MainWindow", "ON"))
        self.Label_Dioda3_5.setText(_translate("MainWindow", "Dioda 5"))
        self.Button_OFF_Dioda3_6.setText(_translate("MainWindow", "OFF"))
        self.Button_ON_Dioda3_6.setText(_translate("MainWindow", "ON"))
        self.Label_Dioda3_6.setText(_translate("MainWindow", "Dioda 5"))
        self.Button_OFF_Dioda3_7.setText(_translate("MainWindow", "OFF"))
        self.Button_ON_Dioda3_7.setText(_translate("MainWindow", "ON"))
        self.Label_Dioda3_7.setText(_translate("MainWindow", "Dioda 6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

